version: '3.2'

services:
  proxy:
    build:
      context: ./proxy
      args:
        - "SSL_DOMAIN"
        - "SSL_EMAIL"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # STATIC_SITE_PATH is the path to your generated website.
      - "${STATIC_SITE_PATH}:/var/www/html"
      - "ssl_certs:/etc/ssl-certs"
      - "acme_sh:/root/.acme.sh"
    restart: unless-stopped
volumes:
  acme_sh:
  ssl_certs: