version: '3.2'

# Production docker file. Adds ursus_builder to rebuild the website when the
# git repo has new commits

services:
  # The search image is not needed to run the website. It's specific to nicolasbouliane.com
  search:
    build: ./search
    environment:
      - "TIMELINE_CLIENT_ID"
      - "TIMELINE_CLIENT_SECRET"
  ursus_builder:
    build:
      context: "./ursus_builder"
    depends_on:
      - search
    environment:
      - "GIT_REPO_URL"
      - "SITE_URL"
    volumes:
      - "ursus_files:/var/ursus/site"
      - "static_site:/var/ursus/output"
  proxy:
    volumes:
      - "static_site:/var/www/html"
volumes:
  ursus_files:
  static_site: